name: DY-LLM
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - aiohappyeyeballs=2.6.1=pyhd8ed1ab_0
  - aiohttp=3.11.18=py311h2dc5d0c_0
  - aiosignal=1.3.2=pyhd8ed1ab_0
  - anyio=4.7.0=py311h06a4308_0
  - argon2-cffi=21.3.0=pyhd3eb1b0_0
  - argon2-cffi-bindings=21.2.0=py311h5eee18b_1
  - arrow-cpp=19.0.0=h865e1df_2
  - asttokens=3.0.0=py311h06a4308_0
  - async-lru=2.0.4=py311h06a4308_0
  - aws-c-auth=0.6.19=h5eee18b_0
  - aws-c-cal=0.5.20=hff2c3d7_3
  - aws-c-common=0.8.5=h166bdaf_0
  - aws-c-compression=0.2.16=hf5f93bc_0
  - aws-c-event-stream=0.2.15=h6a678d5_0
  - aws-c-http=0.6.25=h5eee18b_0
  - aws-c-io=0.13.10=h2666983_0
  - aws-c-mqtt=0.7.13=h5eee18b_0
  - aws-c-s3=0.1.51=hdbd6064_0
  - aws-c-sdkutils=0.1.6=hf5f93bc_1
  - aws-checksums=0.1.13=hf5f93bc_5
  - aws-crt-cpp=0.18.16=h6a678d5_0
  - aws-sdk-cpp=1.11.212=hecad206_0
  - babel=2.16.0=py311h06a4308_0
  - beautifulsoup4=4.12.3=py311h06a4308_0
  - blas=1.0=mkl
  - bleach=6.2.0=py311h06a4308_0
  - boost-cpp=1.82.0=hdb19cb5_2
  - brotli=1.0.9=h166bdaf_9
  - brotli-bin=1.0.9=h166bdaf_9
  - brotli-python=1.0.9=py311h6a678d5_9
  - bzip2=1.0.8=h5eee18b_6
  - c-ares=1.19.1=h5eee18b_0
  - ca-certificates=2025.2.25=h06a4308_0
  - certifi=2025.4.26=py311h06a4308_0
  - cffi=1.17.1=py311h1fdaa30_1
  - colorama=0.4.6=pyhd8ed1ab_1
  - comm=0.2.1=py311h06a4308_0
  - contourpy=1.3.2=py311hd18a35c_0
  - cuda-cccl=12.4.127=0
  - cuda-command-line-tools=11.8.0=0
  - cuda-compiler=12.6.2=0
  - cuda-cudart=11.8.89=0
  - cuda-cudart-dev=11.8.89=0
  - cuda-cuobjdump=12.4.127=0
  - cuda-cupti=11.8.87=0
  - cuda-cuxxfilt=12.4.127=0
  - cuda-documentation=12.4.127=0
  - cuda-driver-dev=12.4.127=0
  - cuda-gdb=12.4.127=0
  - cuda-libraries=11.8.0=0
  - cuda-libraries-dev=12.6.0=0
  - cuda-memcheck=11.8.86=0
  - cuda-nsight=12.4.127=0
  - cuda-nvcc=12.4.131=0
  - cuda-nvdisasm=12.4.127=0
  - cuda-nvml-dev=12.4.127=0
  - cuda-nvprof=12.4.127=0
  - cuda-nvprune=12.4.127=0
  - cuda-nvrtc=11.8.89=0
  - cuda-nvrtc-dev=11.8.89=0
  - cuda-nvtx=11.8.86=0
  - cuda-nvvp=12.4.127=0
  - cuda-opencl=12.4.127=0
  - cuda-opencl-dev=12.4.127=0
  - cuda-profiler-api=12.4.127=0
  - cuda-runtime=11.8.0=0
  - cuda-sanitizer-api=12.4.127=0
  - cuda-toolkit=11.8.0=0
  - cuda-tools=11.8.0=0
  - cuda-visual-tools=12.6.0=0
  - cudatoolkit=11.7.0=hd8887f6_10
  - cycler=0.12.1=pyhd8ed1ab_1
  - cyrus-sasl=2.1.28=h52b45da_1
  - dataclasses=0.8=pyhc8e2a94_3
  - dbus=1.13.18=hb2f20db_0
  - debugpy=1.8.11=py311h6a678d5_0
  - decorator=5.1.1=pyhd3eb1b0_0
  - defusedxml=0.7.1=pyhd3eb1b0_0
  - et_xmlfile=1.1.0=py311h06a4308_0
  - executing=0.8.3=pyhd3eb1b0_0
  - expat=2.7.1=h6a678d5_0
  - filelock=3.17.0=py311h06a4308_0
  - fontconfig=2.14.1=h55d465d_3
  - fonttools=4.57.0=py311h2dc5d0c_0
  - freetype=2.13.3=h4a9f257_0
  - gds-tools=1.9.1.3=0
  - gflags=2.2.2=h5888daf_1005
  - glib=2.78.4=h6a678d5_0
  - glib-tools=2.78.4=h6a678d5_0
  - glog=0.5.0=h48cff8f_0
  - gmp=6.3.0=h6a678d5_0
  - gmpy2=2.2.1=py311h5eee18b_0
  - h11=0.14.0=py311h06a4308_0
  - httpcore=1.0.2=py311h06a4308_0
  - httpx=0.27.0=py311h06a4308_0
  - huggingface_hub=0.30.2=pyhd8ed1ab_0
  - icu=73.1=h6a678d5_0
  - intel-openmp=2025.0.0=h06a4308_1171
  - ipykernel=6.29.5=py311h06a4308_1
  - ipython=9.1.0=py311h06a4308_0
  - ipython_pygments_lexers=1.1.1=py311h06a4308_0
  - ipywidgets=8.1.5=py311h06a4308_0
  - jedi=0.19.2=py311h06a4308_0
  - jinja2=3.1.6=py311h06a4308_0
  - jpeg=9e=h5eee18b_3
  - json5=0.9.25=py311h06a4308_0
  - jsonschema=4.23.0=py311h06a4308_0
  - jsonschema-specifications=2023.7.1=py311h06a4308_0
  - jupyter=1.1.1=py311h06a4308_0
  - jupyter-lsp=2.2.0=py311h06a4308_0
  - jupyter_client=8.6.3=py311h06a4308_0
  - jupyter_console=6.6.3=py311h06a4308_0
  - jupyter_core=5.7.2=py311h06a4308_0
  - jupyter_events=0.12.0=py311h06a4308_0
  - jupyter_server=2.15.0=py311h06a4308_0
  - jupyter_server_terminals=0.5.3=py311h06a4308_0
  - jupyterlab=4.3.4=py311h06a4308_0
  - jupyterlab_pygments=0.3.0=py311h06a4308_0
  - jupyterlab_server=2.27.3=py311h06a4308_0
  - jupyterlab_widgets=3.0.13=py311h06a4308_0
  - kiwisolver=1.4.7=py311hd18a35c_0
  - krb5=1.20.1=h143b758_1
  - lcms2=2.16=h92b89f2_1
  - ld_impl_linux-64=2.40=h12ee557_0
  - lerc=4.0.0=h0aef613_1
  - libabseil=20250127.0=cxx17_h6a678d5_0
  - libblas=3.9.0=1_h86c2bf4_netlib
  - libboost=1.82.0=h109eef0_2
  - libbrotlicommon=1.0.9=h166bdaf_9
  - libbrotlidec=1.0.9=h166bdaf_9
  - libbrotlienc=1.0.9=h166bdaf_9
  - libcblas=3.9.0=8_h3b12eaf_netlib
  - libclang13=14.0.6=default_he11475f_2
  - libcublas=11.11.3.6=0
  - libcublas-dev=11.11.3.6=0
  - libcufft=10.9.0.58=0
  - libcufft-dev=10.9.0.58=0
  - libcufile=1.9.1.3=0
  - libcufile-dev=1.9.1.3=0
  - libcups=2.4.2=h2d74bed_1
  - libcurand=10.3.5.147=0
  - libcurand-dev=10.3.5.147=0
  - libcurl=8.12.1=hc9e6f67_0
  - libcusolver=11.4.1.48=0
  - libcusolver-dev=11.4.1.48=0
  - libcusparse=11.7.5.86=0
  - libcusparse-dev=11.7.5.86=0
  - libdeflate=1.22=hb9d3cd8_0
  - libedit=3.1.20230828=h5eee18b_0
  - libev=4.33=h7f8727e_1
  - libevent=2.1.12=hf998b51_1
  - libffi=3.4.4=h6a678d5_1
  - libgcc=14.2.0=h767d61c_2
  - libgcc-ng=14.2.0=h69a702a_2
  - libgfortran=14.2.0=h69a702a_2
  - libgfortran-ng=14.2.0=h69a702a_2
  - libgfortran5=14.2.0=hf1ad2bd_2
  - libglib=2.78.4=hdc74915_0
  - libgomp=14.2.0=h767d61c_2
  - libgrpc=1.71.0=h2d74bed_0
  - libiconv=1.16=h5eee18b_3
  - liblapack=3.9.0=8_h3b12eaf_netlib
  - libllvm14=14.0.6=hecde1de_4
  - libnghttp2=1.57.0=h2d74bed_0
  - libnpp=11.8.0.86=0
  - libnpp-dev=11.8.0.86=0
  - libnvfatbin=12.4.127=0
  - libnvfatbin-dev=12.4.127=0
  - libnvjitlink=12.4.127=0
  - libnvjitlink-dev=12.4.127=0
  - libnvjpeg=11.9.0.86=0
  - libnvjpeg-dev=11.9.0.86=0
  - libpng=1.6.39=h5eee18b_0
  - libpq=17.4=hdbd6064_0
  - libprotobuf=5.29.3=hc99497a_0
  - libre2-11=2024.07.02=hba17884_3
  - libsodium=1.0.18=h7b6447c_0
  - libssh2=1.11.1=h251f7ec_0
  - libstdcxx=14.2.0=h8f9b012_2
  - libstdcxx-ng=11.2.0=h1234567_1
  - libthrift=0.15.0=h1795dd8_2
  - libtiff=4.7.0=hde9077f_0
  - libuuid=1.41.5=h5eee18b_0
  - libwebp-base=1.5.0=h851e524_0
  - libxcb=1.15=h7f8727e_0
  - libxkbcommon=1.0.1=h097e994_2
  - libxml2=2.13.7=hfdd30dd_0
  - libxslt=1.1.41=h097e994_0
  - llvm-openmp=14.0.6=h9e868ea_0
  - lz4-c=1.9.4=h6a678d5_1
  - markupsafe=3.0.2=py311h5eee18b_0
  - matplotlib=3.10.1=py311h38be061_0
  - matplotlib-base=3.10.1=py311h2b939e6_0
  - matplotlib-inline=0.1.6=py311h06a4308_0
  - minizip=4.0.3=hf59b114_0
  - mistune=3.1.2=py311h06a4308_0
  - mkl=2020.2=256
  - mpc=1.3.1=h5eee18b_0
  - mpfr=4.2.1=h5eee18b_0
  - mpmath=1.3.0=py311h06a4308_0
  - multidict=6.4.3=py311h2dc5d0c_0
  - munkres=1.1.4=pyh9f0ad1d_0
  - mysql=8.4.0=h721767e_2
  - nbclient=0.10.2=py311h06a4308_0
  - nbconvert=7.16.6=py311h06a4308_0
  - nbconvert-core=7.16.6=py311h06a4308_0
  - nbconvert-pandoc=7.16.6=py311h06a4308_0
  - nbformat=5.10.4=py311h06a4308_0
  - ncurses=6.4=h6a678d5_0
  - nest-asyncio=1.6.0=py311h06a4308_0
  - networkx=3.4.2=py311h06a4308_0
  - notebook=7.3.2=py311h06a4308_0
  - notebook-shim=0.2.4=py311h06a4308_0
  - nsight-compute=2024.1.1.4=0
  - nspr=4.36=h5888daf_0
  - nss=3.89.1=h6a678d5_0
  - openjpeg=2.5.2=h0d4d230_1
  - openldap=2.6.4=h42fbc30_0
  - openpyxl=3.1.5=py311h5eee18b_1
  - openssl=3.5.0=h7b32b05_0
  - orc=2.1.1=hd396ef6_0
  - overrides=7.4.0=py311h06a4308_0
  - pandas=2.2.3=py311h7db5c69_3
  - pandoc=2.12=h06a4308_3
  - pandocfilters=1.5.0=pyhd3eb1b0_0
  - parso=0.8.4=py311h06a4308_0
  - pcre2=10.42=hebb0a14_1
  - pexpect=4.8.0=pyhd3eb1b0_3
  - pip=25.1=pyhc872135_2
  - platformdirs=4.3.7=py311h06a4308_0
  - prometheus_client=0.21.1=py311h06a4308_0
  - prompt-toolkit=3.0.43=py311h06a4308_0
  - prompt_toolkit=3.0.43=hd3eb1b0_0
  - propcache=0.3.1=py311h2dc5d0c_0
  - ptyprocess=0.7.0=pyhd3eb1b0_2
  - pure_eval=0.2.2=pyhd3eb1b0_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pygments=2.19.1=py311h06a4308_0
  - pyparsing=3.2.3=pyhd8ed1ab_1
  - pyqt=6.7.1=py311h6a678d5_1
  - pyqt6-sip=13.9.1=py311h5eee18b_1
  - pyside6=6.7.2=py311hfe62871_0
  - pysocks=1.7.1=py311h06a4308_0
  - python=3.11.11=he870216_0
  - python-dateutil=2.9.0post0=py311h06a4308_2
  - python-fastjsonschema=2.20.0=py311h06a4308_0
  - python-json-logger=3.2.1=py311h06a4308_0
  - python-tzdata=2025.2=pyhd8ed1ab_0
  - python-xxhash=3.5.0=py311h9ecbd09_2
  - python_abi=3.11=2_cp311
  - pytorch-cuda=11.8=h7e8668a_6
  - pytorch-mutex=1.0=cuda
  - pytz=2025.2=pyhd8ed1ab_0
  - pyyaml=6.0.2=py311h5eee18b_0
  - pyzmq=26.2.0=py311h6a678d5_0
  - qhull=2020.2=h4bd325d_2
  - qtbase=6.7.3=hdaa5aa8_0
  - qtconsole=5.6.1=py311h06a4308_1
  - qtdeclarative=6.7.3=h6a678d5_0
  - qtpy=2.4.1=py311h06a4308_0
  - qtshadertools=6.7.3=h6a678d5_0
  - qtsvg=6.7.3=he621ea3_0
  - qttools=6.7.3=h80c7b02_0
  - qtwebchannel=6.7.3=h6a678d5_0
  - qtwebengine=6.7.3=h7abb84b_0
  - qtwebsockets=6.7.3=h6a678d5_0
  - re2=2024.07.02=h9925aae_3
  - readline=8.2=h5eee18b_0
  - referencing=0.30.2=py311h06a4308_0
  - regex=2024.11.6=py311h5eee18b_0
  - requests=2.32.3=py311h06a4308_1
  - rfc3339-validator=0.1.4=py311h06a4308_0
  - rfc3986-validator=0.1.1=py311h06a4308_0
  - rpds-py=0.22.3=py311h4aa5aa6_0
  - s2n=1.3.27=h1b5e8cb_0
  - safetensors=0.5.3=py311h448de89_0
  - send2trash=1.8.2=py311h06a4308_1
  - setuptools=75.8.0=py311h06a4308_0
  - sip=6.10.0=py311h6a678d5_0
  - six=1.17.0=py311h06a4308_0
  - snappy=1.2.1=h8bd8927_1
  - sniffio=1.3.0=py311h06a4308_0
  - soupsieve=2.5=py311h06a4308_0
  - sqlite=3.45.3=h5eee18b_0
  - stack_data=0.2.0=pyhd3eb1b0_0
  - tbb=2022.0.0=hdb19cb5_0
  - tbb-devel=2022.0.0=hdb19cb5_0
  - terminado=0.17.1=py311h06a4308_0
  - tinycss2=1.4.0=py311h06a4308_0
  - tk=8.6.14=h39e8969_0
  - tornado=6.4.2=py311h5eee18b_0
  - tqdm=4.67.1=pyhd8ed1ab_1
  - traitlets=5.14.3=py311h06a4308_0
  - transformers=4.51.3=pyhd8ed1ab_0
  - tzdata=2025a=h04d1e81_0
  - unicodedata2=16.0.0=py311h9ecbd09_0
  - utf8proc=2.6.1=h5eee18b_1
  - wcwidth=0.2.5=pyhd3eb1b0_0
  - webencodings=0.5.1=py311h06a4308_1
  - websocket-client=1.8.0=py311h06a4308_0
  - wheel=0.45.1=py311h06a4308_0
  - widgetsnbextension=4.0.13=py311h06a4308_0
  - xcb-util-cursor=0.1.4=h5eee18b_0
  - xxhash=0.8.3=hb9d3cd8_0
  - xz=5.6.4=h5eee18b_1
  - yaml=0.2.5=h7b6447c_0
  - yarl=1.20.0=py311h2dc5d0c_0
  - zeromq=4.3.5=h6a678d5_0
  - zlib=1.2.13=h5eee18b_1
  - zstd=1.5.6=hc292b87_0
  - pip:
      - accelerate==1.6.0
      - aiohttp-cors==0.8.1
      - airportsdata==20250224
      - annotated-types==0.7.0
      - astor==0.8.1
      - attrs==25.3.0
      - bitsandbytes==0.45.5
      - blake3==1.0.4
      - blinker==1.9.0
      - cachetools==5.5.2
      - charset-normalizer==3.4.1
      - click==8.1.8
      - cloudpickle==3.1.1
      - colorful==0.5.6
      - compressed-tensors==0.9.2
      - copent==0.5.7
      - cupy-cuda12x==13.4.1
      - cut-cross-entropy==25.1.1
      - datasets==3.5.0
      - deprecated==1.2.18
      - depyf==0.18.0
      - diffusers==0.33.1
      - dill==0.3.8
      - diskcache==5.6.3
      - distlib==0.3.9
      - distro==1.9.0
      - dnspython==2.7.0
      - docstring-parser==0.16
      - einops==0.8.1
      - email-validator==2.2.0
      - fastapi==0.115.12
      - fastapi-cli==0.0.7
      - fastrlock==0.8.3
      - flask==3.1.0
      - flask-cors==5.0.1
      - frozenlist==1.6.0
      - fsspec==2024.12.0
      - gguf==0.10.0
      - google-api-core==2.24.2
      - google-auth==2.39.0
      - googleapis-common-protos==1.70.0
      - grpcio==1.72.0rc1
      - hf-transfer==0.1.9
      - hf-xet==1.1.0
      - httptools==0.6.4
      - idna==3.10
      - importlib-metadata==8.0.0
      - iniconfig==2.1.0
      - interegular==0.3.3
      - itsdangerous==2.2.0
      - jiter==0.9.0
      - joblib==1.5.0
      - lark==1.2.2
      - lightning==2.1.2
      - lightning-utilities==0.14.3
      - llguidance==0.7.19
      - llvmlite==0.43.0
      - lm-format-enforcer==0.10.11
      - markdown-it-py==3.0.0
      - mdurl==0.1.2
      - mistral-common==1.5.4
      - modelscope==1.25.0
      - msgpack==1.1.0
      - msgspec==0.19.0
      - multiprocess==0.70.16
      - nanobind==2.7.0
      - ninja==1.11.1.4
      - numba==0.60.0
      - numpy==1.26.4
      - nvidia-cublas-cu11==11.11.3.6
      - nvidia-cublas-cu12==12.4.5.8
      - nvidia-cuda-cupti-cu11==11.8.87
      - nvidia-cuda-cupti-cu12==12.4.127
      - nvidia-cuda-nvrtc-cu11==11.8.89
      - nvidia-cuda-nvrtc-cu12==12.4.127
      - nvidia-cuda-runtime-cu11==11.8.89
      - nvidia-cuda-runtime-cu12==12.4.127
      - nvidia-cudnn-cu11==9.1.0.70
      - nvidia-cudnn-cu12==9.1.0.70
      - nvidia-cufft-cu11==10.9.0.58
      - nvidia-cufft-cu12==11.2.1.3
      - nvidia-curand-cu11==10.3.0.86
      - nvidia-curand-cu12==10.3.5.147
      - nvidia-cusolver-cu11==11.4.1.48
      - nvidia-cusolver-cu12==11.6.1.9
      - nvidia-cusparse-cu11==11.7.5.86
      - nvidia-cusparse-cu12==12.3.1.170
      - nvidia-cusparselt-cu12==0.6.2
      - nvidia-ml-py==12.570.86
      - nvidia-nccl-cu11==2.20.5
      - nvidia-nccl-cu12==2.21.5
      - nvidia-nvjitlink-cu12==12.4.127
      - nvidia-nvtx-cu11==11.8.86
      - nvidia-nvtx-cu12==12.4.127
      - openai==1.77.0
      - opencensus==0.11.4
      - opencensus-context==0.1.3
      - opencv-python-headless==4.11.0.86
      - opentelemetry-api==1.26.0
      - opentelemetry-exporter-otlp==1.26.0
      - opentelemetry-exporter-otlp-proto-common==1.26.0
      - opentelemetry-exporter-otlp-proto-grpc==1.26.0
      - opentelemetry-exporter-otlp-proto-http==1.26.0
      - opentelemetry-proto==1.26.0
      - opentelemetry-sdk==1.26.0
      - opentelemetry-semantic-conventions==0.47b0
      - opentelemetry-semantic-conventions-ai==0.4.5
      - outlines==0.1.11
      - outlines-core==0.1.26
      - packaging==25.0
      - partial-json-parser==0.2.1.1.post5
      - patsy==1.0.1
      - peft==0.15.2
      - pillow==11.2.1
      - pluggy==1.5.0
      - prometheus-fastapi-instrumentator==7.1.0
      - proto-plus==1.26.1
      - protobuf==3.20.3
      - psutil==7.0.0
      - ptwt==0.1.9
      - py-cpuinfo==9.0.0
      - py-spy==0.4.0
      - pyairports==2.1.1
      - pyarrow==19.0.1
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.2
      - pybind11==2.13.6
      - pycountry==24.6.1
      - pydantic==2.11.4
      - pydantic-core==2.33.2
      - pytest==8.3.5
      - python-dotenv==1.1.0
      - python-multipart==0.0.20
      - pytorch-lightning==2.5.2
      - pywavelets==1.8.0
      - ray==2.46.0
      - rich==14.0.0
      - rich-toolkit==0.14.4
      - rsa==4.9.1
      - scienceplots==2.1.1
      - scikit-learn==1.6.1
      - scipy==1.15.2
      - seaborn==0.13.2
      - sentencepiece==0.2.0
      - shellingham==1.5.4
      - shtab==1.7.2
      - smart-open==7.1.0
      - starlette==0.46.2
      - statsmodels==0.14.5
      - sympy==1.13.1
      - threadpoolctl==3.6.0
      - tiktoken==0.9.0
      - tokenizers==0.21.1
      - torch==2.6.0
      - torchaudio==2.6.0
      - torchmetrics==1.7.4
      - torchvision==0.21.0
      - triton==3.2.0
      - trl==0.15.2
      - typeguard==4.4.2
      - typer==0.15.3
      - typing-extensions==4.13.2
      - typing-inspection==0.4.0
      - tyro==0.9.19
      - unsloth==2025.5.6
      - unsloth-zoo==2025.5.7
      - urllib3==2.4.0
      - uvicorn==0.34.2
      - uvloop==0.21.0
      - virtualenv==20.30.0
      - vllm==0.8.2
      - watchfiles==1.0.5
      - websockets==15.0.1
      - werkzeug==3.1.3
      - wrapt==1.17.2
      - xformers==0.0.29.post2
      - xgrammar==0.1.16
      - zipp==3.21.0
prefix: /home/dy29/.conda/envs/DY-LLM
